import Foundation
import AppKit

/// Pasteboard UTIs set by password managers / OS to signal "don't save".
/// See https://nspasteboard.org/
enum SkipPasteboardTypes {
    static let concealed     = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient     = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static let all: Set<NSPasteboard.PasteboardType> = [concealed, transient, autoGenerated]
}

enum ClipboardFilter {
    /// Cap image payloads to keep ~/Library/Application Support from bloating
    /// when full-screen screenshots land on the clipboard.
    static let maxImageBytes = 5 * 1024 * 1024  // 5 MB

    static func shouldAccept(types: Set<NSPasteboard.PasteboardType>,
                             text: String?,
                             image: Data?) -> Bool {
        if !SkipPasteboardTypes.all.isDisjoint(with: types) { return false }
        // Validate text and image independently so an image with an empty
        // text representation alongside it still gets accepted.
        return hasValidText(text) || hasValidImage(image)
    }

    static func hasValidText(_ text: String?) -> Bool {
        guard let text else { return false }
        return !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    static func hasValidImage(_ image: Data?) -> Bool {
        guard let image else { return false }
        return image.count <= maxImageBytes
    }
}
