import Foundation
import AppKit

/// Pasteboard UTIs set by password managers / OS to signal "don't save".
/// See https://nspasteboard.org/
enum SkipPasteboardTypes {
    static let concealed     = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient     = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static let all: Set<NSPasteboard.PasteboardType> = [concealed, transient, autoGenerated]
}

enum ClipboardFilter {
    /// Cap image payloads to keep ~/Library/Application Support from bloating
    /// when full-screen screenshots land on the clipboard.
    static let maxImageBytes = 5 * 1024 * 1024  // 5 MB

    static func shouldAccept(types: Set<NSPasteboard.PasteboardType>,
                             text: String?,
                             image: Data?) -> Bool {
        if !SkipPasteboardTypes.all.isDisjoint(with: types) { return false }
        if let text {
            return !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        }
        if let image {
            return image.count <= maxImageBytes
        }
        return false
    }
}
