import Foundation
import AppKit

/// Pasteboard UTIs set by password managers / OS to signal "don't save".
/// See https://nspasteboard.org/
enum SkipPasteboardTypes {
    static let concealed     = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient     = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static let all: Set<NSPasteboard.PasteboardType> = [concealed, transient, autoGenerated]
}

enum ClipboardFilter {
    // ─────────────────────────────────────────────────────────────────────
    // YOUR CALL — see README "Customising the filter".
    //
    // The default honours the nspasteboard.org convention so passwords from
    // Apple Passwords / 1Password / Bitwarden are skipped, and rejects empty
    // payloads. Extend if you want to: cap image size, drop pure-whitespace
    // strings, blocklist particular source apps, etc.
    // ─────────────────────────────────────────────────────────────────────
    static func shouldAccept(types: Set<NSPasteboard.PasteboardType>,
                             text: String?,
                             image: Data?) -> Bool {
        if !SkipPasteboardTypes.all.isDisjoint(with: types) { return false }
        if text == nil && image == nil { return false }
        return true
    }
}
